import{a as f,i as l,S as p}from"./assets/vendor-09d7c26e.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&t(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function t(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const m="43943872-0cd26c97fed3a84845e31fcef";function h(n){return f.get(`https://pixabay.com/api/?key=${m}&q=${n}&image_type=photo&orientation=horizontal&safesearch=true`).then(r=>r.data.hits).catch(r=>console.error(r))}function g(n,r){if(n.length===0){l.error({title:"Error",message:"Изображения, соответствующие вашему запросу, не найдены. Пожалуйста, попробуйте еще раз."});return}const s=n.map(t=>`
    <div class="image-card">
      <a href="${t.largeImageURL}"><img src="${t.webformatURL}" alt="${t.tags}" title=""/></a>
      <div class="image-info">
        <p><span>Просмотры: </span>${t.views}</p>
        <p><span>Загрузки: </span>${t.downloads}</p>
        <p><span>Лайки: </span>${t.likes}</p>
        <p><span>Комментарии: </span>${t.comments}</p>
      </div>
    </div>
  `).join("");r.innerHTML=s}const y=document.querySelector("#search-form"),d=document.querySelector("#search-input"),i=document.querySelector("#gallery"),u=document.querySelector("#loader");let c;y.addEventListener("submit",n=>{n.preventDefault();const r=d.value.trim();if(!r){l.warning({title:"Warning",message:"Пожалуйста, введите ключевое слово для поиска"});return}u.classList.remove("hidden"),h(r).then(s=>{u.classList.add("hidden"),i.innerHTML="",g(s,i),i.querySelectorAll(".image-card a").length>0?(c=new p(".image-card a",{}),i.addEventListener("click",t=>{t.target.nodeName==="IMG"&&(c?c.show():console.error("Lightbox is not initialized."))})):console.error("No images found for lightbox to handle."),d.value=""}).catch(s=>{console.error(s),l.error({title:"Error",message:"Произошла ошибка при загрузке изображений. Пожалуйста, попробуйте еще раз."})})});
//# sourceMappingURL=commonHelpers.js.map
